spring:
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mysql://localhost:3307/auto_trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: autos
    password: autos_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3307/auto_trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    user: autos
    password: autos_pw
  data:
    redis:
      host: localhost
      port: 6379
      username: default        # Redis 6+ ACL 기본 사용자명
      password: autos_redis_pw # 설정한 requirepass 값

jwt:
  secret: ${JWT_SECRET:} # Provide via environment variable or local config
  access-token-valid-seconds: 900       # 15분
  refresh-token-valid-seconds: 1209600  # 14일
  issuer: 'autos-api'
  audience: 'autos-client'

kis:
  base-url: https://openapi.koreainvestment.com:9443
  appkey: ${KIS_APPKEY:}
  appsecret: ${KIS_APPSECRET:}
  overseas:
    auth: ${KIS_OVERSEAS_AUTH:}
  token:
    redis-key: KIS:ACCESS_TOKEN         # 토큰 캐시 키
    safety-seconds: 600                 # 만료 n초 전이면 미리 갱신(버퍼)

quotes:
  daily:
    cron:
      morning: "0 0 9 * * MON-FRI"
      midday: "0 0 12 * * MON-FRI"
      closing: "0 31 15 * * MON-FRI"
      afterHours: "0 5 18 * * MON-FRI"
