spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_trading?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 0505
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate      # 스키마는 Flyway가 만들고, JPA는 검증만
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true # 기존 DB에 적용 시작점 인정
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: change-me-please-very-long-secret
    access-exp-min: 60