-- V2__quote_cache.sql  (오류 원인: CREATE INDEX IF NOT EXISTS 제거, 타입 JPA 엔티티와 일치)
CREATE TABLE IF NOT EXISTS quote_cache (
                                           symbol_id              BIGINT      NOT NULL PRIMARY KEY,
                                           price                  BIGINT      NOT NULL,
                                           prev_diff              BIGINT      DEFAULT 0,
                                           change_rate            DOUBLE,
                                           change_sign            INT,
                                           open_price             BIGINT,
                                           high_price             BIGINT,
                                           low_price              BIGINT,
                                           upper_limit            BIGINT,
                                           lower_limit            BIGINT,
                                           ref_price              BIGINT,
                                           volume                 BIGINT,
                                           amount                 BIGINT,
                                           volume_rate_vs_prev    DOUBLE,
                                           foreign_net_buy_qty    BIGINT,
                                           program_net_buy_qty    BIGINT,
                                           shares_outstanding     BIGINT,
                                           market_cap             BIGINT,
                                           per                    DOUBLE,
                                           pbr                    DOUBLE,
                                           eps                    DOUBLE,
                                           bps                    DOUBLE,
                                           foreign_holding_ratio  DOUBLE,
                                           high52w                BIGINT,
                                           high52w_date           DATE,
                                           high52w_diff_rate      DOUBLE,
                                           low52w                 BIGINT,
                                           low52w_date            DATE,
                                           low52w_diff_rate       DOUBLE,
                                           item_status_code       VARCHAR(3),
                                           credit_allowed         BOOLEAN,
                                           short_sell_allowed     BOOLEAN,
                                           margin_rate            VARCHAR(16),
                                           market_warn_code       VARCHAR(4),
                                           temp_halt              BOOLEAN,
                                           stac_month             CHAR(2),
                                           updated_at             TIMESTAMP NOT NULL
                                                                              DEFAULT CURRENT_TIMESTAMP
                                               ON UPDATE CURRENT_TIMESTAMP,
                                           CONSTRAINT fk_quote_symbol
                                               FOREIGN KEY (symbol_id) REFERENCES symbols(id) ON DELETE CASCADE
);